name: "Build: skyscraper"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: true
        default: '1.0.6'
      arch:
        description: 'Target architecture'
        required: true
        default: 'armhf'
        type: choice
        options: [armhf, arm64]
      distro:
        description: 'Debian version'
        required: true
        default: 'bookworm'
        type: choice
        options: [bookworm, trixie]

concurrency:
  group: build-skyscraper-${{ inputs.arch }}-${{ inputs.distro }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build-group.yml
    with:
      group: skyscraper
      version: ${{ inputs.version }}
      arch: ${{ inputs.arch }}
      distro: ${{ inputs.distro }}
